version: 2

sphinx:
  configuration: doc/source/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - develop
