#! /usr/bin/env python
# -*- coding: utf-8 -*-
# papis-short-help: Convert zotero library to papis library

import tempfile
import sys
import os
import papis.bibtex
import papis.api
import papis.commands
import papis.config
import yaml

if len(sys.argv) < 2:
    print("Usage: papis zotero bibfile <papis add flags>")
    sys.exit(1)

bib_file = sys.argv[1]
add_flags = sys.argv[2:]
print(add_flags)
entries = papis.bibtex.bibtex_to_dict(bib_file)


def add(entry, pdf_file=None):
    temp = tempfile.mktemp()
    fd = open(temp, 'w+')
    yaml.dump(entry, fd, default_flow_style=False)
    fd.close()
    papis.commands.main(
        [
            'add', pdf_file or '--no-document', '--from-yaml', temp
        ] + add_flags
    )


for entry in entries:
    print('INFO: Processing ref %s' % entry['ref'])
    pdf_file = None
    if 'file' in entry.keys():
        pdf_file = entry.get('file').split(':')[1]
        print('\tINFO: File field detected (%s)' % pdf_file)
        if not os.path.exists(pdf_file):
            print('\tWARNING: Path (%s) not found! Ignoring it' % pdf_file)
            del entry['file']
            pdf_file = None
    add(entry, pdf_file)



#vim-run: python3 % ../tests/zotero/zotero.bib --open --edit
