#! /usr/bin/env python3
# -*- coding: utf-8 -*-
"""Start a web server listening on port 23119. This server is
compatible with the `zotero connector`. This means that if zotero is
*not* running, you can have items from your web browser added directly
into papis.

This is a rough port of
https://raw.githubusercontent.com/zotero/zotero/master/chrome/content/zotero/xpcom/server_connector.js

"""

import json
import os
import argparse
import logging
import http.server
import papis.config
import papis.document
import papis.commands.add
import papis.crossref

logger = logging.getLogger("zotero-serve")

connector_api_version = 2
zotero_version = "5.0.25"
zotero_port = 23119

def zotero_data_to_papis_data(item):
    # {'itemType': 'book',
    # 'language': 'en',
    # 'shortTitle': 'Nuclear Collective Motion',
    # 'DOI': '10.1142/6721',
    # 'accessDate': '2018-07-09T22:57:55Z',
    # 'extra': 'DOI: 10.1142/6721',
    # 'creators': [{'creatorType': 'author',
        # 'firstName': 'David J',
        # 'lastName': 'Rowe'}],
    # 'publisher': 'WORLD SCIENTIFIC',
    # 'ISBN': '9789812790644 9789812790668',
    # 'url': 'http://www.worldscientific.com/worldscibooks/10.1142/6721',
    # 'notes': [],
    # 'seeAlso': [],
    # 'attachments': [],
    # 'tags': [],
    # 'date': '05/2010',
    # 'libraryCatalog': 'Crossref',
    # 'title': 'Nuclear Collective Motion: Models and Theory',
    # 'id': 'SL2sa7hx'}

    data = item

    if data.get('id'):
        data['id']
        del data['id']

    if data.get('DOI'):
        data['doi'] = data['DOI']
        data.update(papis.crossref.doi_to_data(data['doi']))
        del data['DOI']

    if data.get('itemType'):
        data['type'] = data.get('itemType')

    if data.get('tags') and isinstance(data.get('tags'), list):
        data['tags'] = " ".join(data['tags'])

    return data


class Command(papis.commands.Command):

    def init(self):
        self.parser = self.get_subparsers().add_parser(
            "",
            help="Start a zotero-connector server"
        )

        self.parser.add_argument(
            "--port",
            help="Port to listen to",
            action="store",
            default=zotero_port,
            type=int
        )

        self.parser.add_argument(
            "--bind",
            help="Address to bind",
            action="store",
            dest="address",
            default="localhost"
        )

        # TODO: no clue on how to do this
        # self.parser.add_argument(
        #     "--fork",
        #     help="Fork the server in background",
        #     action="store_true"
        # )

    def main(self):
        global logger
        server_address = (self.args.address, self.args.port)
        httpd = http.server.HTTPServer(
            server_address,
            PapisRequestHandler
        )
        print("Starting server")
        httpd.serve_forever()

# def papis_add(item):
    # # This should just call a papis function that given a dict of
    # # properties spit out the correct info.yaml and saves it.
    # # I still have to figure out where PDFs are taken
    # print("Adding the document to your library")
    # document = papis.document.from_data(item)
    # lib_dir = os.path.expanduser(papis.config.get('dir'))
    # outdir = os.path.join(lib_dir, papis.utils.clean_document_name(item["title"]))
    # os.makedirs(outdir)
    # document.set_folder(outdir)
    # document.save()

# HTTPRequestHandler class
class PapisRequestHandler(http.server.BaseHTTPRequestHandler):

    def log_message(self, fmt, *args):
        global logger
        print(fmt % args)
        return

    def set_zotero_headers(self):
        self.send_header("X-Zotero-Version",
                         zotero_version)
        self.send_header("X-Zotero-Connector-API-Version",
                         connector_api_version)
        self.end_headers()

    def read_input(self):
        length = int(self.headers['content-length'])
        return self.rfile.read(length)

    def pong(self, POST = True):
        global logger
        print("pong")
        # Pong must respond to ping on both GET and POST
        # It must accepts application/json and text/plain
        if not POST: # GET
            print("GET request")
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.set_zotero_headers()
            response = '<!DOCTYPE html><html><head>'+\
                       '<title>Zotero Connector Server is Available</title></head>'+\
	               '<body>Zotero Connector Server is Available</body></html>'
        else: # POST
            print("POST request")
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.set_zotero_headers()

            response = json.dumps({"prefs":{"automaticSnapshots":
                                            papis.config.get('snapshot')}})

        self.wfile.write(bytes(response, "utf8"))

    def papis_collection(self):
        print("Getting library name")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.set_zotero_headers()
        response = json.dumps(
            {"libraryID":1,
             "libraryName":papis.config.get_lib(),
             "libraryEditable":True, # I'm not aware of a read-only papis mode
             "editable":True,    # collection-level parameters
             "id":None,          # collection-level
             "name": papis.config.get_lib()# collection if collection, else library
            })
        self.wfile.write(bytes(response, "utf8"))

    def add(self):
        # Info or debug?
        print("Adding paper from zotero connector")
        rawinput = self.read_input()
        data = json.loads(rawinput.decode('utf8'))
        source_uri = data['uri'] # source page
        # debug info
        # Add all papers
        for item in data['items']:
            print(item)
            papis_item = zotero_data_to_papis_data(item)
            print('item', papis_item)
            # papis.commands.add.run(
                # [],
                # data=item
            # )
            #papis_add(item)
        self.send_response(201) # Created
        self.set_zotero_headers()

    def snapshot(self):
        logger.warning("Snapshot not implemented")
        self.send_response(201) # Created
        self.set_zotero_headers()
        return

    def do_POST(self):
        if self.path == "/connector/ping":
            self.pong()
        elif self.path == '/connector/getSelectedCollection':
            self.papis_collection()
        elif self.path == '/connector/saveSnapshot':
            self.snapshot()
        elif self.path == '/connector/saveItems':
            self.add()
        return

    def do_GET(self):
        if self.path == "/connector/ping":
            self.pong(POST = False)

if __name__ == "__main__":
    cmd = Command()
    cmd.init()
    cmd.args = cmd.parser.parse_args()
    cmd.main()
