#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# papis-short-help: Download citation using scihub.org
# Copyright © 2017 Alejandro Gallo. GPLv3
import sys
import papis.api
import papis.commands


def usage():
    print("Usage: papis hubation <papis-search> <add-flags>")


if len(sys.argv) < 2:
    search = ""
else:
    search = sys.argv[1]
    if search in ['-h', '--help']:
        usage()
        sys.exit(0)

add_flags = sys.argv[2:]

documents = papis.api.get_documents_in_lib(
    papis.api.get_lib(),
    search=search
)

doc = papis.api.pick_doc(
    documents
)

if 'citations' not in doc.keys():
    print('Document does not have any citations')
    sys.exit(1)

doi = papis.api.pick([d.get('doi') for d in doc['citations']])
doi or sys.exit(0)

print('DOI %s selected' % doi)

papis.commands.main(
    [
        'scihub', doi
    ] + add_flags
)

