#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# papis-short-help: Convert zotero library to papis library
# Copyright 2017 Alejandro Gallo. GPLv3
import tempfile
import sys
import os
import papis.bibtex
import papis.api
import papis.commands
import papis.config
import papis.utils
import yaml


def usage():
    print("Usage: papis zotero bibfile <papis add flags>")


if len(sys.argv) < 2:
    usage()
    sys.exit(1)


bib_file = sys.argv[1]
add_flags = sys.argv[2:]


if not os.path.exists(bib_file):
    print('ERROR: Bib file (%s) not found!' % bib_file)
    usage()
    sys.exit(1)


entries = papis.bibtex.bibtex_to_dict(bib_file)


def add(entry, pdf_file=None):
    temp = tempfile.mktemp()
    fd = open(temp, 'w+')
    yaml.dump(entry, fd, default_flow_style=False)
    fd.close()
    papis.commands.main(
        [
            '-l', papis.api.get_lib(),
            'add', pdf_file or '--no-document', '--from-yaml', temp
        ] + add_flags
    )


for entry in entries:
    for basic_field in ['ref', 'author', 'title']:
        if basic_field not in entry.keys():
            print(entry)
            entry[basic_field] = papis.utils.input(
                '%s Not found, please insert' % basic_field,
                default="???????"
            )
    print('INFO: Processing  |   ref: %s' % entry.get('ref'))
    print('                  |Author: %s' % entry.get('author'))
    print('                  | Title: %s' % entry.get('title'))
    print('                  |')
    pdf_file = None
    if 'file' in entry.keys():
        pdf_file = entry.get('file').split(':')[1]
        pdf_file = os.path.join(os.path.dirname(bib_file), pdf_file)
        print('\tINFO: File field detected (%s)' % pdf_file)
        if not os.path.exists(pdf_file):
            print('\tWARNING: Path (%s) not found! Ignoring it' % pdf_file)
            del entry['file']
            pdf_file = None
    add(entry, pdf_file)
